import type { Metadata } from 'next'

import './globals.css'
import Provider from './Providers/ThemeProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: 'light' }}>
      <body
        className={`h-screen bg-background-light dark:bg-background-dark transitiona ease-in-out   flex justify-center items-center`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
